# Generated by Django 3.1.7 on 2021-02-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_auto_20210219_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ManyToManyField(to='empresas.Empresa')),
            ],
        ),
    ]
