# Generated by Django 3.1.7 on 2021-02-20 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210219_2337'),
        ('plataforma', '0003_auto_20210219_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='empresa',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
