# Generated by Django 3.1.7 on 2021-02-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210219_2337'),
        ('plataforma', '0004_auto_20210219_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='empresa',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='empresa',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
