# Generated by Django 3.1.7 on 2021-02-20 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('plataforma', '0005_auto_20210219_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
