# Generated by Django 3.1.7 on 2021-02-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_auto_20210219_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='usuario',
        ),
    ]
