# Generated by Django 3.1.7 on 2021-02-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('plataforma', '0012_plataforma_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='usuario',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
