# Generated by Django 3.1.7 on 2021-02-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210219_2337'),
        ('plataforma', '0013_auto_20210219_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='usuario',
            new_name='id_usuario',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='id_empresa',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='empresa',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='empresa',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
