# Generated by Django 3.1.7 on 2021-02-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_auto_20210220_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='id_empresa',
            new_name='id_empresas',
        ),
    ]
