# Generated by Django 3.1.7 on 2021-02-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_auto_20210220_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='empresa',
        ),
    ]
