# Generated by Django 3.1.7 on 2021-02-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_auto_20210220_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
